site_name: Wavy Node
site_url: https://wavynode.com
repo_url: https://github.com/wavy-safe
theme: 
  name: material
  favicon: img/favicon.ico
  logo: img/wavyNode.png
  locale: es
  language: es
  features:
    - content.code.copy
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - admonition
