site_name: Wavy Node
site_url: https://wavynode.com
repo_url: https://github.com/WavyNode

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/wavyNode.png
  language: es  # Idioma por defecto de la UI del tema
  features:
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

plugins:
  - search
  - i18n:
      default_language: es
      languages:
        - locale: es
          name: Español
          default: true
          build: true
          nav:
            - Inicio: index.md
            - Notificaciones: notifications.md
            - API:
                - Uso de la API: api/index.md
                - V1:
                    - Addresses: api/v1/addresses.md
                    - API keys: api/v1/api-keys.md
                    - Chains: api/v1/chains.md
                    - Wallets: api/v1/wallets.md
        - locale: en
          name: English
          build: true
          nav:
            - Home: en/index.md
            - Notifications: en/notifications.md
            - API:
                - Getting Started: en/api/index.md
                - V1:
                    - Addresses: en/api/v1/addresses.md
                    - API keys: en/api/v1/api-keys.md
                    - Chains: en/api/v1/chains.md
                    - Wallets: en/api/v1/wallets.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.details
  - admonition
