name: Build and Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main 
    tags:
      - '*' 
  pull_request:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install MkDocs and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mkdocs-static-i18n==1.1
          # pip install mkdocs mkdocs-material # Add other dependencies as needed

      - name: Build MkDocs site
        run: mkdocs build

      - name: Copy CNAME
        run: cp CNAME site/

        # pushes site/ contents to branch gh-pages (where it is being published from) 
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site # The directory where MkDocs builds the site
